CONST_SOURCE_FOLDER = "Pokedex/"
CONST_DESTINATION_FOLDER = "new/"
CONST_ERROR_MSG_SOURCE = "source"
CONST_ERROR_MSG_DESTINATION = "destination"

#PDF.PY RELATED

CONST_PDF_ROOT_DIRECTORY = './pdf_files/'